config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
#   # 
get("/", { :controller => "places", :action => "index" })
get("/places", { :controller => "places", :action => "index" })
get("/places", :controller => "places", :action => "show")

#   # Defines the root path route ("/")
#   # get("/", { :controller => "articles", :action => "index" })
#   # 
  resources "places"


  resources "entries"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  # talks to the "entries" table
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  # talks to the "places" table
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
    if params[:place_id]
      @entry.place_id = params[:place_id]
      place = Place.find(params[:place_id])
      @entry.title = "Trip to #{place.name}"
    end
    @existing_entry = Entry.find_by(place_id: params[:place_id]) if params[:place_id]
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to @entry.place
    else
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :occurred_on, :place_id)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all 

  end
  
  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to new_entry_path(place_id: @place.id)
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end



  # def france
  # end

  # def florida
  # end

  # def colorado
  # end

  # def montana
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_with model: @entry do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :occurred_on %>
    <%= form.date_field :occurred_on %>
  </div>

  <%= form.hidden_field :place_id %>

  <div>
    <%= form.submit "Create Entry" %>
  </div>
<% end %>

<% if @existing_entry %>
  <%= link_to "Back", @existing_entry %>
<% else %>
  <%= link_to "Back to Places", places_path %>
<% end %>

app/views/entries/show.html.erb
<h1><%= @entry.place.name %></h1>

<p><strong>Title:</strong> <%= @entry.title %></p>

<p><strong>Description:</strong> <%= @entry.description %></p>

<p><strong>Occurred on:</strong> <%= @entry.occurred_on %></p>

<p><%= link_to "New Post", new_entry_path(place_id: @entry.place_id) %></p>

<p><%= link_to "Back to Places", places_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>The Places I've Been</h1>

<ul>
	<% @places.each do |place| %>
		<li><%= link_to place.name, place %></li>
	<% end %>
</ul>

<%= link_to "New Place", new_place_path %>


<!--
<form action="/entry">
	<input type="text" name="Title" value="<%= @place%>

	<button>Submit</button>
</form>


<ul>
	
	<li><%= link_to "France", "/places/France" %></li>

	<li><%= link_to "Florida", "/places/Florida" %></li>

	<li><%= link_to "Colorado", "/places/Colorado" %></li>

	<li><%= link_to "Montana", "/place/Montana" %></li>

	<li><%= link_to "New Places", "/places" %></li>
</ul>
-->

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with model: @place do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit "Create Place" %>
  </div>
<% end %>

<%= link_to "Back to Places", places_path %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<% @place.entries.each do |entry| %>
  <h2><%= entry.title %></h2>
  <p><%= entry.description %></p>
  <p>Occurred on: <%= entry.occurred_on %></p>
  <hr>
<% end %>

<%= link_to "New Post", new_entry_path(place_id: @place.id) %>

<%= link_to "Back to Places", places_path %>